stages:
  - test
  - run

test:
  stage: test
  image: rust:latest
  script:
    - cd 2023
    - echo "Testing AoC 2023"
    - cargo test

run:
  stage: run
  image: rust:latest
  script:
    - cd 2023
    - echo "Running AoC 2023"
    - cargo run
