stages:
  - test
  - run

cache:
  key: "$CI_COMMIT_SHA"
  paths:
    - "2023/target/"
    - "2023/Cargo.lock"

test:
  stage: test
  image: rust:latest
  script:
    - cd 2023
    - echo "Testing AoC 2023"
    - cargo test

run:
  stage: run
  image: rust:latest
  script:
    - cd 2023
    - echo "Running AoC 2023"
    - cargo run
